-- SELECT
SELECT * FROM TBL_MEMBER;
SELECT * FROM TBL_ADMIN;
SELECT * FROM TBL_BOOK;
SELECT * FROM TBL_REVIEW;
SELECT * FROM TBL_POINT;
SELECT * FROM TBL_POINT_LIST;
SELECT * FROM TBL_MEMBER_PICK;
SELECT * FROM TBL_MEMBER_CART;
SELECT * FROM TBL_SALED_BOOK;