-- TRUNCATE
TRUNCATE TABLE TBL_MEMBER;
TRUNCATE TABLE TBL_ADMIN;
TRUNCATE TABLE TBL_BOOK;
TRUNCATE TABLE TBL_REVIEW;
TRUNCATE TABLE TBL_POINT;
TRUNCATE TABLE TBL_POINT_LIST;
TRUNCATE TABLE TBL_MEMBER_PICK;
TRUNCATE TABLE TBL_MEMBER_CART;
TRUNCATE TABLE TBL_SALED_BOOK;